# tasks file for roles/osp-instance-delete
- name: Delete instances
  os_server:
    name: "{{ item }}"
    region_name: RegionOne
    state: absent
  loop:
    - app1
    - app2
    - frontend
    - db