- hosts: localhost
  tasks:
  - name: Create workstation inventory
    add_host:
       name: "workstation-{{OSP_GUID}}.rhpds.opentlc.com"
       group: workstation
  - name: Show hosts
    debug:
      msg: Added host workstation-{{OSP_GUID}}.rhpds.opentlc.com

- hosts: workstation
  become: yes
  roles:
    - osp-servers

