# Fetch OSP facts

- hosts: workstation
  gather_facts: true
  roles:
  - name: osp-facts

# Setup front-end load balancer tier

- name: setup load-balancer tier
  hosts: frontends
  become: yes
  roles:
    - name: lb-tier

# Setup application servers tier

- name: setup app tier
  hosts: apps
  become: yes
  roles:
    - name: app-tier

# Setup database tier

- name: setup database tier
  become: yes
  hosts: appdbs
  roles:
    - name: db-tier
