---
# vars file for osp.servers
frontend:
  name: frontend
  state: present
  image: rhel-guest
  key_name: ansible_ssh
  flavor: m2.small
  security_group: frontend
  meta_group: frontends
  meta_deployment_name: QA
app1:
  name: app1
  state: present
  image: rhel-guest
  key_name: ansible_ssh
  flavor: m2.small
  security_group: apps
  meta_group: apps
  meta_deployment_name: QA
app2:
  name: app2
  state: present
  image: rhel-guest
  key_name: ansible_ssh
  flavor: m2.small
  security_group: apps
  meta_group: apps
  meta_deployment_name: QA
db:
  name: db
  state: present
  image: rhel-guest
  key_name: ansible_ssh
  flavor: m2.small
  security_group: db
  meta_group: appdbs
  meta_deployment_name: QA
